//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AppError {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppError() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.AppError", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Continue..
        /// </summary>
        internal static string _100 {
            get {
                return ResourceManager.GetString("100", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Switching protocols..
        /// </summary>
        internal static string _101 {
            get {
                return ResourceManager.GetString("101", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Okay - The client request has succeeded  This status code indicates that the Web server has successfully processed the request.
        /// </summary>
        internal static string _200 {
            get {
                return ResourceManager.GetString("200", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Created..
        /// </summary>
        internal static string _201 {
            get {
                return ResourceManager.GetString("201", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accepted..
        /// </summary>
        internal static string _202 {
            get {
                return ResourceManager.GetString("202", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Non-authoritative information..
        /// </summary>
        internal static string _203 {
            get {
                return ResourceManager.GetString("203", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No content..
        /// </summary>
        internal static string _204 {
            get {
                return ResourceManager.GetString("204", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset content..
        /// </summary>
        internal static string _205 {
            get {
                return ResourceManager.GetString("205", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Partial content..
        /// </summary>
        internal static string _206 {
            get {
                return ResourceManager.GetString("206", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Object moved..
        /// </summary>
        internal static string _302 {
            get {
                return ResourceManager.GetString("302", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not modified. The client requests a document that is already in its cache and the document has not been modified since it was cached. The client uses the cached copy of the document, instead of downloading it from the server.
        /// </summary>
        internal static string _304 {
            get {
                return ResourceManager.GetString("304", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Temporary redirect..
        /// </summary>
        internal static string _307 {
            get {
                return ResourceManager.GetString("307", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bad request..
        /// </summary>
        internal static string _400 {
            get {
                return ResourceManager.GetString("400", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Access denied..
        /// </summary>
        internal static string _401 {
            get {
                return ResourceManager.GetString("401", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logon failed. The logon attempt is unsuccessful, probably because of a user name or password that is not valid..
        /// </summary>
        internal static string _401_1 {
            get {
                return ResourceManager.GetString("401.1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logon failed due to server configuration..
        /// </summary>
        internal static string _401_2 {
            get {
                return ResourceManager.GetString("401.2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unauthorized due to ACL on resource. This indicates a problem with NTFS permissions. This error may occur even if the permissions are correct for the file that you are trying to access. For example, you see this error if the IUSR account does not have access to the C:\Winnt\System32\Inetsrv directory..
        /// </summary>
        internal static string _401_3 {
            get {
                return ResourceManager.GetString("401.3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Authorization failed by filter..
        /// </summary>
        internal static string _401_4 {
            get {
                return ResourceManager.GetString("401.4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Authorization failed by ISAPI/CGI application..
        /// </summary>
        internal static string _401_5 {
            get {
                return ResourceManager.GetString("401.5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Access denied by URL authorization policy on the Web server. This error code is specific to IIS 6.0..
        /// </summary>
        internal static string _401_7 {
            get {
                return ResourceManager.GetString("401.7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forbidden..
        /// </summary>
        internal static string _403 {
            get {
                return ResourceManager.GetString("403", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Execute access forbidden. The following are two common causes of this error message:
        ///•	You do not have enough Execute permissions. For example, you may receive this error message if you try to access an ASP page in a directory where permissions are set to None, or you try to execute a CGI script in a directory with Scripts Only permissions. 
        ///•	The script mapping for the file type that you are trying to execute is not set up to recognize the verb that you are using (for example, GET or POST)..
        /// </summary>
        internal static string _403_1 {
            get {
                return ResourceManager.GetString("403.1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid configuration..
        /// </summary>
        internal static string _403_11 {
            get {
                return ResourceManager.GetString("403.11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password change..
        /// </summary>
        internal static string _403_111 {
            get {
                return ResourceManager.GetString("403.111", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mapper denied access. The page that you want to access requires a client certificate, but the user ID that is mapped to your client certificate has been denied access to the file..
        /// </summary>
        internal static string _403_12 {
            get {
                return ResourceManager.GetString("403.12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Client certificate revoked..
        /// </summary>
        internal static string _403_13 {
            get {
                return ResourceManager.GetString("403.13", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Directory listing denied..
        /// </summary>
        internal static string _403_14 {
            get {
                return ResourceManager.GetString("403.14", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Client Access Licenses exceeded..
        /// </summary>
        internal static string _403_15 {
            get {
                return ResourceManager.GetString("403.15", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Client certificate is un-trusted or invalid..
        /// </summary>
        internal static string _403_16 {
            get {
                return ResourceManager.GetString("403.16", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Client certificate has expired or is not yet valid..
        /// </summary>
        internal static string _403_17 {
            get {
                return ResourceManager.GetString("403.17", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot execute requested URL in the current application pool. This error code is specific to IIS 6.0..
        /// </summary>
        internal static string _403_18 {
            get {
                return ResourceManager.GetString("403.18", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot execute CGIs for the client in this application pool. This error code is specific to IIS 6.0..
        /// </summary>
        internal static string _403_19 {
            get {
                return ResourceManager.GetString("403.19", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Read access forbidden. Verify that you have Read access to the directory. Also, if you are using a default document, verify that the document exists..
        /// </summary>
        internal static string _403_2 {
            get {
                return ResourceManager.GetString("403.2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Passport logon failed. This error code is specific to IIS 6.0..
        /// </summary>
        internal static string _403_21 {
            get {
                return ResourceManager.GetString("403.21", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Write access forbidden. Verify that you have Write access to the directory.
        /// </summary>
        internal static string _403_3 {
            get {
                return ResourceManager.GetString("403.3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SSL required. Use HTTPS instead of HTTP to access the page..
        /// </summary>
        internal static string _403_4 {
            get {
                return ResourceManager.GetString("403.4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SSL 128 required..
        /// </summary>
        internal static string _403_5 {
            get {
                return ResourceManager.GetString("403.5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IP address rejected..
        /// </summary>
        internal static string _403_6 {
            get {
                return ResourceManager.GetString("403.6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Client certificate required. You do not have a valid client certificate installed.
        /// </summary>
        internal static string _403_7 {
            get {
                return ResourceManager.GetString("403.7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Site access denied..
        /// </summary>
        internal static string _403_8 {
            get {
                return ResourceManager.GetString("403.8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Too many users. The number of users who are connected to the server exceeds the connection limit..
        /// </summary>
        internal static string _403_9 {
            get {
                return ResourceManager.GetString("403.9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not found. This error may occur if the file that you are trying to access has been moved or deleted..
        /// </summary>
        internal static string _404 {
            get {
                return ResourceManager.GetString("404", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File or directory not found..
        /// </summary>
        internal static string _4041 {
            get {
                return ResourceManager.GetString("4041", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Web site not accessible on the requested port..
        /// </summary>
        internal static string _404_1 {
            get {
                return ResourceManager.GetString("404.1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Web service extension lockdown policy prevents this request..
        /// </summary>
        internal static string _404_2 {
            get {
                return ResourceManager.GetString("404.2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MIME map policy prevents this request..
        /// </summary>
        internal static string _404_3 {
            get {
                return ResourceManager.GetString("404.3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HTTP verb used to access this page is not allowed (method not allowed)..
        /// </summary>
        internal static string _405 {
            get {
                return ResourceManager.GetString("405", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Client browser does not accept the MIME type of the requested page..
        /// </summary>
        internal static string _406 {
            get {
                return ResourceManager.GetString("406", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Proxy authentication required..
        /// </summary>
        internal static string _407 {
            get {
                return ResourceManager.GetString("407", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Precondition failed..
        /// </summary>
        internal static string _412 {
            get {
                return ResourceManager.GetString("412", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Request entity too large..
        /// </summary>
        internal static string _413 {
            get {
                return ResourceManager.GetString("413", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Request-URL too long..
        /// </summary>
        internal static string _414 {
            get {
                return ResourceManager.GetString("414", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unsupported media type..
        /// </summary>
        internal static string _415 {
            get {
                return ResourceManager.GetString("415", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Requested range not satisfying..
        /// </summary>
        internal static string _416 {
            get {
                return ResourceManager.GetString("416", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Execution failed..
        /// </summary>
        internal static string _417 {
            get {
                return ResourceManager.GetString("417", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Locked error..
        /// </summary>
        internal static string _423 {
            get {
                return ResourceManager.GetString("423", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Internal server error.  You see this error message for a wide variety of server-side errors..
        /// </summary>
        internal static string _500 {
            get {
                return ResourceManager.GetString("500", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Internal ASP error. You receive this error message when you try to load an ASP page that has errors in the code..
        /// </summary>
        internal static string _500_1 {
            get {
                return ResourceManager.GetString("500.1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application is busy restarting on the Web server. Indicates that you tried to load an ASP page while IIS was in the process of restarting the application. This message should disappear when you refresh the page. If you refresh the page and the message appears again, it may be caused by antivirus software that is scanning your Global.asa file..
        /// </summary>
        internal static string _500_12 {
            get {
                return ResourceManager.GetString("500.12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Web server is too busy..
        /// </summary>
        internal static string _500_13 {
            get {
                return ResourceManager.GetString("500.13", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Direct requests for Global.asa are not allowed..
        /// </summary>
        internal static string _500_15 {
            get {
                return ResourceManager.GetString("500.15", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UNC authorization credentials incorrect. This error code is specific to IIS 6.0..
        /// </summary>
        internal static string _500_16 {
            get {
                return ResourceManager.GetString("500.16", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to URL authorization store cannot be opened. This error code is specific to IIS 6.0..
        /// </summary>
        internal static string _500_18 {
            get {
                return ResourceManager.GetString("500.18", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Header values specify a configuration that is not implemented..
        /// </summary>
        internal static string _501 {
            get {
                return ResourceManager.GetString("501", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bad Gateway.  Web server received an invalid response while acting as a gateway or proxy. You receive this error message when you try to run a CGI script that does not return a valid set of HTTP headers..
        /// </summary>
        internal static string _502 {
            get {
                return ResourceManager.GetString("502", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CGI application timeout..
        /// </summary>
        internal static string _502_1 {
            get {
                return ResourceManager.GetString("502.1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error in CGI application..
        /// </summary>
        internal static string _502_2 {
            get {
                return ResourceManager.GetString("502.2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service unavailable. This error code is specific to IIS 6.0..
        /// </summary>
        internal static string _503 {
            get {
                return ResourceManager.GetString("503", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gateway timeout..
        /// </summary>
        internal static string _504 {
            get {
                return ResourceManager.GetString("504", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HTTP version not supported..
        /// </summary>
        internal static string _505 {
            get {
                return ResourceManager.GetString("505", resourceCulture);
            }
        }
    }
}
