//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RCA.App_GlobalResources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Common {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Common() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("RCA.App_GlobalResources.Common", typeof(Common).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Server Error!.
        /// </summary>
        public static string App_Error_Head {
            get {
                return ResourceManager.GetString("App_Error_Head", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Report To Us.
        /// </summary>
        public static string App_Error_ReportUs {
            get {
                return ResourceManager.GetString("App_Error_ReportUs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The server encountered a temporary error and could not complete your request. &lt;br/&gt; Please try back in few minutes. &lt;br/&gt; &lt;br/&gt; &lt;br/&gt; &lt;br/&gt; If you still receive this error, please report to the system administrator..
        /// </summary>
        public static string App_Error_Text {
            get {
                return ResourceManager.GetString("App_Error_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English.
        /// </summary>
        public static string btn_Language {
            get {
                return ResourceManager.GetString("btn_Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A+.
        /// </summary>
        public static string btn_Large {
            get {
                return ResourceManager.GetString("btn_Large", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A+.
        /// </summary>
        public static string btn_Larger {
            get {
                return ResourceManager.GetString("btn_Larger", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set to Largest Font.
        /// </summary>
        public static string btn_LargerToolTip {
            get {
                return ResourceManager.GetString("btn_LargerToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set to Larger Font.
        /// </summary>
        public static string btn_LargeToolTip {
            get {
                return ResourceManager.GetString("btn_LargeToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A.
        /// </summary>
        public static string btn_Medium {
            get {
                return ResourceManager.GetString("btn_Medium", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set to Medium Font.
        /// </summary>
        public static string btn_MediumToolTip {
            get {
                return ResourceManager.GetString("btn_MediumToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A-.
        /// </summary>
        public static string btn_Small {
            get {
                return ResourceManager.GetString("btn_Small", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A-.
        /// </summary>
        public static string btn_Smallest {
            get {
                return ResourceManager.GetString("btn_Smallest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set to Smallest Font.
        /// </summary>
        public static string btn_SmallestToolTip {
            get {
                return ResourceManager.GetString("btn_SmallestToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set to Smaller Font.
        /// </summary>
        public static string btn_SmallToolTip {
            get {
                return ResourceManager.GetString("btn_SmallToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A.
        /// </summary>
        public static string btnABlack {
            get {
                return ResourceManager.GetString("btnABlack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to High Contrast.
        /// </summary>
        public static string btnABlackToolTip {
            get {
                return ResourceManager.GetString("btnABlackToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A.
        /// </summary>
        public static string btnAWhite {
            get {
                return ResourceManager.GetString("btnAWhite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Low Contrast.
        /// </summary>
        public static string btnAWhiteToolTip {
            get {
                return ResourceManager.GetString("btnAWhiteToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string btnCancel {
            get {
                return ResourceManager.GetString("btnCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact Us.
        /// </summary>
        public static string btnContactUs {
            get {
                return ResourceManager.GetString("btnContactUs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        public static string btnHome {
            get {
                return ResourceManager.GetString("btnHome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LogIn.
        /// </summary>
        public static string btnlogin {
            get {
                return ResourceManager.GetString("btnlogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string btnSave {
            get {
                return ResourceManager.GetString("btnSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mumbai, IN.
        /// </summary>
        public static string CityMumbai {
            get {
                return ResourceManager.GetString("CityMumbai", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to द्वारे विकसित.
        /// </summary>
        public static string developedBy {
            get {
                return ResourceManager.GetString("developedBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Key Person.
        /// </summary>
        public static string heading {
            get {
                return ResourceManager.GetString("heading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log Out.
        /// </summary>
        public static string HeadLoginStatus {
            get {
                return ResourceManager.GetString("HeadLoginStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1001/Home&apos;&gt;Home.
        /// </summary>
        public static string HomepagePath {
            get {
                return ResourceManager.GetString("HomepagePath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change Password.
        /// </summary>
        public static string HyperLink1 {
            get {
                return ResourceManager.GetString("HyperLink1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maharashtra Information Technology Corporation Limited..
        /// </summary>
        public static string imgMahaIT_alt {
            get {
                return ResourceManager.GetString("imgMahaIT_alt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This is the official website of Housing Department, &lt;br/&gt;&lt;span&gt; Government of Maharashtra. ©2018 All Rights Reserved.&lt;/span&gt;.
        /// </summary>
        public static string lbl_copyright {
            get {
                return ResourceManager.GetString("lbl_copyright", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Developed By : .
        /// </summary>
        public static string lbl_developedby {
            get {
                return ResourceManager.GetString("lbl_developedby", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maharashtra Rent Control Act (Housing department) &lt;br/&gt;&lt;span&gt;Government of Maharashtra&lt;/span&gt;.
        /// </summary>
        public static string lbl_headTitle {
            get {
                return ResourceManager.GetString("lbl_headTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skip to Content.
        /// </summary>
        public static string lbl_skipToContent {
            get {
                return ResourceManager.GetString("lbl_skipToContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skip to Navigation.
        /// </summary>
        public static string lbl_skipToNav {
            get {
                return ResourceManager.GetString("lbl_skipToNav", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maharashtra Rent Control Act (Housing department), Government of Maharashtra.
        /// </summary>
        public static string lbldepName {
            get {
                return ResourceManager.GetString("lbldepName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select District.
        /// </summary>
        public static string lblDistrict {
            get {
                return ResourceManager.GetString("lblDistrict", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Keyword Search.
        /// </summary>
        public static string lblKeywordsearch {
            get {
                return ResourceManager.GetString("lblKeywordsearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Latest News.
        /// </summary>
        public static string lblNews {
            get {
                return ResourceManager.GetString("lblNews", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to More News Update.
        /// </summary>
        public static string lblNewsMore {
            get {
                return ResourceManager.GetString("lblNewsMore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        public static string lblSearchBTN {
            get {
                return ResourceManager.GetString("lblSearchBTN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are searching for this word :.
        /// </summary>
        public static string lblSearchword {
            get {
                return ResourceManager.GetString("lblSearchword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Site Map.
        /// </summary>
        public static string lblsitemap {
            get {
                return ResourceManager.GetString("lblsitemap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Website Start Date :.
        /// </summary>
        public static string lblStartDate {
            get {
                return ResourceManager.GetString("lblStartDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Today&apos;s Count.
        /// </summary>
        public static string lblTodaysVisitor {
            get {
                return ResourceManager.GetString("lblTodaysVisitor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Visitors :.
        /// </summary>
        public static string lblTotalVisitor {
            get {
                return ResourceManager.GetString("lblTotalVisitor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search Site.
        /// </summary>
        public static string lblViewPartnersHeading {
            get {
                return ResourceManager.GetString("lblViewPartnersHeading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Government of India.
        /// </summary>
        public static string NationalEmblem_alt {
            get {
                return ResourceManager.GetString("NationalEmblem_alt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        public static string Search_btn {
            get {
                return ResourceManager.GetString("Search_btn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search here.
        /// </summary>
        public static string searchTxtBox {
            get {
                return ResourceManager.GetString("searchTxtBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are here :.
        /// </summary>
        public static string SitemapMsg {
            get {
                return ResourceManager.GetString("SitemapMsg", resourceCulture);
            }
        }
    }
}
