//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class General {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal General() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.General", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        internal static string Add_btn {
            get {
                return ResourceManager.GetString("Add_btn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Server Error!.
        /// </summary>
        internal static string App_Error_Head {
            get {
                return ResourceManager.GetString("App_Error_Head", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Report To Us.
        /// </summary>
        internal static string App_Error_ReportUs {
            get {
                return ResourceManager.GetString("App_Error_ReportUs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The server encountered a temporary error and could not complete your request. &lt;br/&gt; Please try back in few minutes. &lt;br/&gt; &lt;br/&gt; &lt;br/&gt; &lt;br/&gt; If you still receive this error, please report to the system administrator..
        /// </summary>
        internal static string App_Error_Text {
            get {
                return ResourceManager.GetString("App_Error_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back.
        /// </summary>
        internal static string Back_btn {
            get {
                return ResourceManager.GetString("Back_btn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BannerHead.
        /// </summary>
        internal static string BannerHead {
            get {
                return ResourceManager.GetString("BannerHead", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A.
        /// </summary>
        internal static string btnABlack {
            get {
                return ResourceManager.GetString("btnABlack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A.
        /// </summary>
        internal static string btnAWhite {
            get {
                return ResourceManager.GetString("btnAWhite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear.
        /// </summary>
        internal static string btnClear {
            get {
                return ResourceManager.GetString("btnClear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear.
        /// </summary>
        internal static string btnCLear1 {
            get {
                return ResourceManager.GetString("btnCLear1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        internal static string btnCommSerch {
            get {
                return ResourceManager.GetString("btnCommSerch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact Us.
        /// </summary>
        internal static string btnContactUs {
            get {
                return ResourceManager.GetString("btnContactUs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        internal static string btnHome {
            get {
                return ResourceManager.GetString("btnHome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LogIn.
        /// </summary>
        internal static string btnlogin {
            get {
                return ResourceManager.GetString("btnlogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset.
        /// </summary>
        internal static string btnreset {
            get {
                return ResourceManager.GetString("btnreset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        internal static string btnSearch {
            get {
                return ResourceManager.GetString("btnSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        internal static string btnSearchGR {
            get {
                return ResourceManager.GetString("btnSearchGR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send Complaint.
        /// </summary>
        internal static string btnSendComplaint {
            get {
                return ResourceManager.GetString("btnSendComplaint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Site Map.
        /// </summary>
        internal static string btnSiteMap {
            get {
                return ResourceManager.GetString("btnSiteMap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Submit.
        /// </summary>
        internal static string btnSubmit {
            get {
                return ResourceManager.GetString("btnSubmit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A+.
        /// </summary>
        internal static string btn_Large {
            get {
                return ResourceManager.GetString("btn_Large", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A++.
        /// </summary>
        internal static string btn_Larger {
            get {
                return ResourceManager.GetString("btn_Larger", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A.
        /// </summary>
        internal static string btn_Medium {
            get {
                return ResourceManager.GetString("btn_Medium", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A-.
        /// </summary>
        internal static string btn_Small {
            get {
                return ResourceManager.GetString("btn_Small", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A--.
        /// </summary>
        internal static string btn_Smallest {
            get {
                return ResourceManager.GetString("btn_Smallest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string Cancel_btn {
            get {
                return ResourceManager.GetString("Cancel_btn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CMS Head.
        /// </summary>
        internal static string CMSHeading {
            get {
                return ResourceManager.GetString("CMSHeading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CMS More Head.
        /// </summary>
        internal static string CMSMoreHeading {
            get {
                return ResourceManager.GetString("CMSMoreHeading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Continue.
        /// </summary>
        internal static string Continue_btn {
            get {
                return ResourceManager.GetString("Continue_btn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CreateUser.
        /// </summary>
        internal static string CreateUser {
            get {
                return ResourceManager.GetString("CreateUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        internal static string Delete_btn {
            get {
                return ResourceManager.GetString("Delete_btn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Department of MahaIT.
        /// </summary>
        internal static string DepartmentName {
            get {
                return ResourceManager.GetString("DepartmentName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Housing Department Logo.
        /// </summary>
        internal static string DeptLogo_Alt {
            get {
                return ResourceManager.GetString("DeptLogo_Alt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Department Title.
        /// </summary>
        internal static string DeptLogo_Title {
            get {
                return ResourceManager.GetString("DeptLogo_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        internal static string Edit_btn {
            get {
                return ResourceManager.GetString("Edit_btn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E Mail.
        /// </summary>
        internal static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We are sorry for inconvenience.
        /// </summary>
        internal static string ErrorHandlerMsg {
            get {
                return ResourceManager.GetString("ErrorHandlerMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maharashtra Rent Control Act.
        /// </summary>
        internal static string HajLogo_alt {
            get {
                return ResourceManager.GetString("HajLogo_alt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log Out.
        /// </summary>
        internal static string HeadLoginStatus {
            get {
                return ResourceManager.GetString("HeadLoginStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change Password.
        /// </summary>
        internal static string HyperLink1 {
            get {
                return ResourceManager.GetString("HyperLink1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MahaIT Ltd..
        /// </summary>
        internal static string imgMahaOnline_alt {
            get {
                return ResourceManager.GetString("imgMahaOnline_alt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Important Link.
        /// </summary>
        internal static string ImportantLink {
            get {
                return ResourceManager.GetString("ImportantLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Key Person.
        /// </summary>
        internal static string KeyPerson {
            get {
                return ResourceManager.GetString("KeyPerson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Key person.
        /// </summary>
        internal static string KeyPersonHeader {
            get {
                return ResourceManager.GetString("KeyPersonHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address.
        /// </summary>
        internal static string LblAddress {
            get {
                return ResourceManager.GetString("LblAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Photo Gallery.
        /// </summary>
        internal static string lblAlbum {
            get {
                return ResourceManager.GetString("lblAlbum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string lblAmendmentDocName {
            get {
                return ResourceManager.GetString("lblAmendmentDocName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter Case Number To Search.
        /// </summary>
        internal static string lblCaseNo {
            get {
                return ResourceManager.GetString("lblCaseNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Track Case.
        /// </summary>
        internal static string lblCaseTrack {
            get {
                return ResourceManager.GetString("lblCaseTrack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Circular.
        /// </summary>
        internal static string lblCircular {
            get {
                return ResourceManager.GetString("lblCircular", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to From Date.
        /// </summary>
        internal static string lblCommFromDate {
            get {
                return ResourceManager.GetString("lblCommFromDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Commisionerate Orders.
        /// </summary>
        internal static string LblCommisionerateOrders {
            get {
                return ResourceManager.GetString("LblCommisionerateOrders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To Date.
        /// </summary>
        internal static string lblCommToDate {
            get {
                return ResourceManager.GetString("lblCommToDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Online Grivience.
        /// </summary>
        internal static string lblComplaintPageTitle {
            get {
                return ResourceManager.GetString("lblComplaintPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Online Grivience.
        /// </summary>
        internal static string lblComplaintPageTitle1 {
            get {
                return ResourceManager.GetString("lblComplaintPageTitle1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address.
        /// </summary>
        internal static string lblComp_Address {
            get {
                return ResourceManager.GetString("lblComp_Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What is Second Number among Following List &lt;/br&gt;.
        /// </summary>
        internal static string lblComp_Captcha {
            get {
                return ResourceManager.GetString("lblComp_Captcha", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Suggetions/Complaints.
        /// </summary>
        internal static string lblComp_Complaints {
            get {
                return ResourceManager.GetString("lblComp_Complaints", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Country.
        /// </summary>
        internal static string lblComp_Country {
            get {
                return ResourceManager.GetString("lblComp_Country", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Department.
        /// </summary>
        internal static string lblComp_Department {
            get {
                return ResourceManager.GetString("lblComp_Department", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to District.
        /// </summary>
        internal static string lblComp_District {
            get {
                return ResourceManager.GetString("lblComp_District", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EmailId.
        /// </summary>
        internal static string lblComp_EmailId {
            get {
                return ResourceManager.GetString("lblComp_EmailId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Full Name.
        /// </summary>
        internal static string lblComp_FullName {
            get {
                return ResourceManager.GetString("lblComp_FullName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mobile No.
        /// </summary>
        internal static string lblComp_MobileNo {
            get {
                return ResourceManager.GetString("lblComp_MobileNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to State.
        /// </summary>
        internal static string lblComp_State {
            get {
                return ResourceManager.GetString("lblComp_State", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sub Types Of Societies.
        /// </summary>
        internal static string lblComp_SubTypesofSocieties {
            get {
                return ResourceManager.GetString("lblComp_SubTypesofSocieties", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Taluka.
        /// </summary>
        internal static string lblComp_Taluka {
            get {
                return ResourceManager.GetString("lblComp_Taluka", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Types Complaint.
        /// </summary>
        internal static string lblComp_TypeofComplaint {
            get {
                return ResourceManager.GetString("lblComp_TypeofComplaint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Website owned by Maharashtra Fire Services, India.
        /// </summary>
        internal static string lblCopyright {
            get {
                return ResourceManager.GetString("lblCopyright", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Country.
        /// </summary>
        internal static string lblCountry {
            get {
                return ResourceManager.GetString("lblCountry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Court Orders.
        /// </summary>
        internal static string lblCourtOrders {
            get {
                return ResourceManager.GetString("lblCourtOrders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date.
        /// </summary>
        internal static string lblCreatedDate {
            get {
                return ResourceManager.GetString("lblCreatedDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date.
        /// </summary>
        internal static string lblDate {
            get {
                return ResourceManager.GetString("lblDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Department.
        /// </summary>
        internal static string lblDepartment {
            get {
                return ResourceManager.GetString("lblDepartment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maharashtra Rent Control Act (Housing Department), Government of Maharashtra.
        /// </summary>
        internal static string lbldepName {
            get {
                return ResourceManager.GetString("lbldepName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to District.
        /// </summary>
        internal static string LblDistrict {
            get {
                return ResourceManager.GetString("LblDistrict", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Division.
        /// </summary>
        internal static string lblDivision {
            get {
                return ResourceManager.GetString("lblDivision", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Document Name.
        /// </summary>
        internal static string lblDocName {
            get {
                return ResourceManager.GetString("lblDocName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Document Type.
        /// </summary>
        internal static string lblDocType {
            get {
                return ResourceManager.GetString("lblDocType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Document Type.
        /// </summary>
        internal static string lblDocumentType {
            get {
                return ResourceManager.GetString("lblDocumentType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EmailId.
        /// </summary>
        internal static string lblEmailId {
            get {
                return ResourceManager.GetString("lblEmailId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Factory Type.
        /// </summary>
        internal static string lblFactoryType {
            get {
                return ResourceManager.GetString("lblFactoryType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Feedback.
        /// </summary>
        internal static string lblFeedback {
            get {
                return ResourceManager.GetString("lblFeedback", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FromDate.
        /// </summary>
        internal static string lblFromDate {
            get {
                return ResourceManager.GetString("lblFromDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home Heading.
        /// </summary>
        internal static string lblHomeHeading {
            get {
                return ResourceManager.GetString("lblHomeHeading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Honourable Minister.
        /// </summary>
        internal static string lblHonourableMinisterHeading {
            get {
                return ResourceManager.GetString("lblHonourableMinisterHeading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message....
        /// </summary>
        internal static string lblKeyPersonMsg {
            get {
                return ResourceManager.GetString("lblKeyPersonMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Keyword Search.
        /// </summary>
        internal static string lblKeywordsearch {
            get {
                return ResourceManager.GetString("lblKeywordsearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to KeyWord Search.
        /// </summary>
        internal static string lblKKeywordSearch {
            get {
                return ResourceManager.GetString("lblKKeywordSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mobile No.
        /// </summary>
        internal static string LblMobileNo {
            get {
                return ResourceManager.GetString("LblMobileNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string lblName {
            get {
                return ResourceManager.GetString("lblName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Latest News.
        /// </summary>
        internal static string lblNews {
            get {
                return ResourceManager.GetString("lblNews", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to More News Update.
        /// </summary>
        internal static string lblNewsMore {
            get {
                return ResourceManager.GetString("lblNewsMore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click here for new user registration.
        /// </summary>
        internal static string lblNewUserRegister {
            get {
                return ResourceManager.GetString("lblNewUserRegister", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Path.
        /// </summary>
        internal static string lblPath {
            get {
                return ResourceManager.GetString("lblPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reprints of the Act.
        /// </summary>
        internal static string lblReprint {
            get {
                return ResourceManager.GetString("lblReprint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Season.
        /// </summary>
        internal static string Lblseason {
            get {
                return ResourceManager.GetString("Lblseason", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to State.
        /// </summary>
        internal static string Lblstate {
            get {
                return ResourceManager.GetString("Lblstate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tahasil.
        /// </summary>
        internal static string LblTaluka {
            get {
                return ResourceManager.GetString("LblTaluka", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MILL-WISE AND SEASON-WISE STOCK OF LEVY AND NON LEVY SUGAR AS ON 30-09-2011 [Quantity in M.T.].
        /// </summary>
        internal static string lblText {
            get {
                return ResourceManager.GetString("lblText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter Answer.
        /// </summary>
        internal static string lblTextCapachAns {
            get {
                return ResourceManager.GetString("lblTextCapachAns", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Downloads.
        /// </summary>
        internal static string lblTitelDownloads {
            get {
                return ResourceManager.GetString("lblTitelDownloads", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mantri Samitee Meeting Proceedings.
        /// </summary>
        internal static string lblTitelMantriSamiti {
            get {
                return ResourceManager.GetString("lblTitelMantriSamiti", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GOM: Home Page.
        /// </summary>
        internal static string lblTitle {
            get {
                return ResourceManager.GetString("lblTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List Of Sugar Factories.
        /// </summary>
        internal static string lblTitleGetSugarListFactories {
            get {
                return ResourceManager.GetString("lblTitleGetSugarListFactories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Laws By Laws Act.
        /// </summary>
        internal static string lblTittleLawsByAct {
            get {
                return ResourceManager.GetString("lblTittleLawsByAct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To Date.
        /// </summary>
        internal static string lblTodate {
            get {
                return ResourceManager.GetString("lblTodate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amendments to Co-operative Act.
        /// </summary>
        internal static string lbl_AmendmentsTitle {
            get {
                return ResourceManager.GetString("lbl_AmendmentsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Awards and Achievement.
        /// </summary>
        internal static string lbl_AwardsTitle {
            get {
                return ResourceManager.GetString("lbl_AwardsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to © This is the official website of Housing Department, Government of Maharashtra. All Rights Reserved..
        /// </summary>
        internal static string lbl_copyright {
            get {
                return ResourceManager.GetString("lbl_copyright", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Developed By :.
        /// </summary>
        internal static string lbl_developedby {
            get {
                return ResourceManager.GetString("lbl_developedby", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Feedback.
        /// </summary>
        internal static string lbl_Feedback {
            get {
                return ResourceManager.GetString("lbl_Feedback", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GR/Circular/LawsbyLaws.
        /// </summary>
        internal static string lbl_GR {
            get {
                return ResourceManager.GetString("lbl_GR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GR/Circular/LawsByLaws.
        /// </summary>
        internal static string lbl_GRHeading {
            get {
                return ResourceManager.GetString("lbl_GRHeading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Government Resolutions.
        /// </summary>
        internal static string lbl_GRTitle {
            get {
                return ResourceManager.GetString("lbl_GRTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maharashtra Rent Control Act (Housing Department) &lt;br/&gt;&lt;span&gt;Government of Maharashtra&lt;/span&gt;.
        /// </summary>
        internal static string lbl_headTitle {
            get {
                return ResourceManager.GetString("lbl_headTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maintained By MahaIT ltd..
        /// </summary>
        internal static string lbl_mahaonline {
            get {
                return ResourceManager.GetString("lbl_mahaonline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Right To Information(RTI).
        /// </summary>
        internal static string lbl_RTIPageDetail {
            get {
                return ResourceManager.GetString("lbl_RTIPageDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skip to Content.
        /// </summary>
        internal static string lbl_skipToContent {
            get {
                return ResourceManager.GetString("lbl_skipToContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skip to Navigation.
        /// </summary>
        internal static string lbl_skipToNav {
            get {
                return ResourceManager.GetString("lbl_skipToNav", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sugar Release Order.
        /// </summary>
        internal static string lbl_SugarReleaseOrderTitle {
            get {
                return ResourceManager.GetString("lbl_SugarReleaseOrderTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tenders.
        /// </summary>
        internal static string lbl_Tenders {
            get {
                return ResourceManager.GetString("lbl_Tenders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome to Maharashtra Fire Services, India.
        /// </summary>
        internal static string lbl_welcome {
            get {
                return ResourceManager.GetString("lbl_welcome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Archives.
        /// </summary>
        internal static string lnkArchives {
            get {
                return ResourceManager.GetString("lnkArchives", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Citizen Charter.
        /// </summary>
        internal static string lnkCitizenCharter {
            get {
                return ResourceManager.GetString("lnkCitizenCharter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English.
        /// </summary>
        internal static string lnkCulture {
            get {
                return ResourceManager.GetString("lnkCulture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FAQ.
        /// </summary>
        internal static string lnkFAQ {
            get {
                return ResourceManager.GetString("lnkFAQ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Privacy Policy.
        /// </summary>
        internal static string lnkPrivacyPolicy {
            get {
                return ResourceManager.GetString("lnkPrivacyPolicy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RTI.
        /// </summary>
        internal static string lnkRTI {
            get {
                return ResourceManager.GetString("lnkRTI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Government of Maharashtra.
        /// </summary>
        internal static string MaharashtraLogo_alt {
            get {
                return ResourceManager.GetString("MaharashtraLogo_alt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maharashtra Logo Title.
        /// </summary>
        internal static string MaharashtraLogo_Title {
            get {
                return ResourceManager.GetString("MaharashtraLogo_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Government of India.
        /// </summary>
        internal static string NationalEmblem_alt {
            get {
                return ResourceManager.GetString("NationalEmblem_alt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New.
        /// </summary>
        internal static string New_btn {
            get {
                return ResourceManager.GetString("New_btn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Other Link.
        /// </summary>
        internal static string OtherLink {
            get {
                return ResourceManager.GetString("OtherLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        internal static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Print.
        /// </summary>
        internal static string Print_btn {
            get {
                return ResourceManager.GetString("Print_btn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quick Link.
        /// </summary>
        internal static string QuickLink {
            get {
                return ResourceManager.GetString("QuickLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm Password.
        /// </summary>
        internal static string RetypePassword {
            get {
                return ResourceManager.GetString("RetypePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        internal static string Save_btn {
            get {
                return ResourceManager.GetString("Save_btn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        internal static string searchBTN {
            get {
                return ResourceManager.GetString("searchBTN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        internal static string Search_btn {
            get {
                return ResourceManager.GetString("Search_btn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Site Header Logo.
        /// </summary>
        internal static string SiteHeader_Alt {
            get {
                return ResourceManager.GetString("SiteHeader_Alt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Site Header Title.
        /// </summary>
        internal static string SiteHeader_Title {
            get {
                return ResourceManager.GetString("SiteHeader_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 436885, 987809, 51994.
        /// </summary>
        internal static string String {
            get {
                return ResourceManager.GetString("String", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /Information.
        /// </summary>
        internal static string String1 {
            get {
                return ResourceManager.GetString("String1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maharashtra Fire Services.
        /// </summary>
        internal static string String2 {
            get {
                return ResourceManager.GetString("String2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UserName.
        /// </summary>
        internal static string UserName {
            get {
                return ResourceManager.GetString("UserName", resourceCulture);
            }
        }
    }
}
